using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace DarkwoodRandomizer.Plugin.Settings
{
    internal static class ItemPools
    {
        private static readonly string ItemPoolsDirectory = Path.Combine(DarkwoodRandomizerPlugin.PluginPath, "ItemPools");

        internal static IEnumerable<string> PoolNames =
            [nameof(ALL_ITEMS), nameof(AMMO_ITEMS), nameof(CONSUMABLE_ITEMS), nameof(DEBUG_ITEMS),
                nameof(HOME_ITEMS), nameof(JOURNAL_ITEMS), nameof(KEY_ITEMS), nameof(MAP_ITEMS),
                nameof(MATERIAL_ITEMS), nameof(MISC_ITEMS), nameof(QUEST_ITEMS), nameof(THROWN_ITEMS),
                nameof(TRAP_ITEMS), nameof(UTILITY_ITEMS), nameof(WEAPON_ITEMS), nameof(XP_ITEMS)];


        internal static Dictionary<string, string>? VendorNightTrader => GetPoolFromFile(nameof(VendorNightTrader));
        internal static Dictionary<string, string>? VendorPiotrek => GetPoolFromFile(nameof(VendorPiotrek));
        internal static Dictionary<string, string>? VendorWolfman => GetPoolFromFile(nameof(VendorWolfman));
        
        internal static Dictionary<string, string>? CharacterLoot => GetPoolFromFile(nameof(CharacterLoot));



        private static Dictionary<string, string>? GetPoolFromFile(string poolName)
        {
            string path = Path.Combine(ItemPoolsDirectory, $"{poolName}.txt");
            if (!File.Exists(path))
                return null;

            StreamReader reader = new StreamReader(path);
            Dictionary<string, string> items = new();
            while (!reader.EndOfStream)
            {
                string[] tokens = reader.ReadLine().Trim().Split();
                if (tokens.Length == 0)
                    continue;

                if (PoolNames.Contains(tokens[0]))
                {
                    if (tokens.Length > 1 && int.TryParse(tokens[1], out int timesToAdd))
                        for (int i = 0; i < timesToAdd; i++)
                            foreach (KeyValuePair<string, string> item in (Dictionary<string, string>)typeof(ItemPools).GetField(tokens[0]).GetValue(null))
                                items.Add(item.Key, item.Value);
                    else
                        foreach (KeyValuePair<string, string> item in (Dictionary<string, string>)typeof(ItemPools).GetField(tokens[0]).GetValue(null))
                            items.Add(item.Key, item.Value);
                }
                else if (ALL_ITEMS.ContainsKey(tokens[0]))
                {
                    if (tokens.Length > 1 && int.TryParse(tokens[1], out int timesToAdd))
                        for (int i = 0; i < timesToAdd; i++)
                            items.Add(tokens[0], ALL_ITEMS[tokens[0]]);
                    else
                        items.Add(tokens[0], ALL_ITEMS[tokens[0]]);
                }
            }
            reader.Close();
            return items;
        }


        internal static Dictionary<string, string> ALL_ITEMS = new()
        {
            ["fists"] = "InventoryItems/_other/fists",
            ["hammer"] = "InventoryItems/_other/hammer",
            ["healthUpgrade"] = "InventoryItems/_other/healthUpgrade",
            ["playerUpgradeIngredient"] = "InventoryItems/_other/playerUpgradeIngredient",
            ["recipe"] = "InventoryItems/_other/recipe",
            ["staminaUpgrade"] = "InventoryItems/_other/staminaUpgrade",
            ["workbenchUpgrade_01"] = "InventoryItems/_other/workbenchUpgrade_01",
            ["workbenchUpgrade_02"] = "InventoryItems/_other/workbenchUpgrade_02",
            ["workbenchUpgrade_03"] = "InventoryItems/_other/workbenchUpgrade_03",
            ["workbenchUpgrade_04"] = "InventoryItems/_other/workbenchUpgrade_04",
            ["workbenchUpgrade_05"] = "InventoryItems/_other/workbenchUpgrade_05",
            ["workbenchUpgrade_06"] = "InventoryItems/_other/workbenchUpgrade_06",
            ["workbenchUpgrade_07"] = "InventoryItems/_other/workbenchUpgrade_07",
            ["workbenchUpgrade_08"] = "InventoryItems/_other/workbenchUpgrade_08",
            ["ammo_clip_mediumCal"] = "InventoryItems/ammo/ammo_clip_mediumCal",
            ["ammo_clip_smallCal"] = "InventoryItems/ammo/ammo_clip_smallCal",
            ["ammo_single_mediumCal"] = "InventoryItems/ammo/ammo_single_mediumCal",
            ["ammo_single_pellet"] = "InventoryItems/ammo/ammo_single_pellet",
            ["ammo_single_shotgun"] = "InventoryItems/ammo/ammo_single_shotgun",
            ["battery9v"] = "InventoryItems/ammo/battery9v",
            ["acid"] = "InventoryItems/consumables/acid",
            ["alcohol"] = "InventoryItems/consumables/alcohol",
            ["antidote_poison"] = "InventoryItems/consumables/antidote_poison",
            ["bandages"] = "InventoryItems/consumables/bandages",
            ["bandages_alcohol"] = "InventoryItems/consumables/bandages_alcohol",
            ["bread"] = "InventoryItems/consumables/bread",
            ["chicken_egg"] = "InventoryItems/consumables/chicken_egg",
            ["chicken_egg_red"] = "InventoryItems/consumables/chicken_egg_red",
            ["dead_rat"] = "InventoryItems/consumables/dead_rat",
            ["fish"] = "InventoryItems/consumables/fish",
            ["lifePotion"] = "InventoryItems/consumables/lifePotion",
            ["pills"] = "InventoryItems/consumables/pills",
            ["pills_02"] = "InventoryItems/consumables/pills_02",
            ["potato_01"] = "InventoryItems/consumables/potato_01",
            ["soup_01"] = "InventoryItems/consumables/soup_01",
            ["exp_bio2_meat_mutated"] = "InventoryItems/expObjs/exp_bio2_meat_mutated",
            ["exp_bio2_mushroom_01"] = "InventoryItems/expObjs/exp_bio2_mushroom_01",
            ["exp_bio2_nightMushroom_01"] = "InventoryItems/expObjs/exp_bio2_nightMushroom_01",
            ["exp_bio3_meat_mutated"] = "InventoryItems/expObjs/exp_bio3_meat_mutated",
            ["exp_bio3_mushroom_meat_01"] = "InventoryItems/expObjs/exp_bio3_mushroom_meat_01",
            ["exp_bio3_nightMushroom_01"] = "InventoryItems/expObjs/exp_bio3_nightMushroom_01",
            ["exp_cockroach_mutated"] = "InventoryItems/expObjs/exp_cockroach_mutated",
            ["exp_epickiEXP"] = "InventoryItems/expObjs/exp_epickiEXP",
            ["exp_meat_mutated"] = "InventoryItems/expObjs/exp_meat_mutated",
            ["exp_mushroom"] = "InventoryItems/expObjs/exp_mushroom",
            ["exp_nightMushroom"] = "InventoryItems/expObjs/exp_nightMushroom",
            ["exp_piskle"] = "InventoryItems/expObjs/exp_piskle",
            ["firecraft_boltHandle"] = "InventoryItems/firearms/firecraft_boltHandle",
            ["firecraft_handgunFrame"] = "InventoryItems/firearms/firecraft_handgunFrame",
            ["firecraft_longBarrel"] = "InventoryItems/firearms/firecraft_longBarrel",
            ["firecraft_tubularMagazine"] = "InventoryItems/firearms/firecraft_tubularMagazine",
            ["firecraft_weaponParts"] = "InventoryItems/firearms/firecraft_weaponParts",
            ["weapon_assault_01_burst"] = "InventoryItems/firearms/weapon_assault_01_burst",
            ["weapon_flamethrower_homeMade"] = "InventoryItems/firearms/weapon_flamethrower_homeMade",
            ["weapon_flamethrower_military"] = "InventoryItems/firearms/weapon_flamethrower_military",
            ["weapon_pistol_01_pellet"] = "InventoryItems/firearms/weapon_pistol_01_pellet",
            ["weapon_pistol_02_semi"] = "InventoryItems/firearms/weapon_pistol_02_semi",
            ["weapon_pistol_03_oneShot"] = "InventoryItems/firearms/weapon_pistol_03_oneShot",
            ["weapon_rifle_01_pellet"] = "InventoryItems/firearms/weapon_rifle_01_pellet",
            ["weapon_rifle_02_boltAction"] = "InventoryItems/firearms/weapon_rifle_02_boltAction",
            ["weapon_shotgun_01_breakAction_Double"] = "InventoryItems/firearms/weapon_shotgun_01_breakAction_Double",
            ["weapon_shotgun_02_pumpAction"] = "InventoryItems/firearms/weapon_shotgun_02_pumpAction",
            ["weapon_shotgun_03_singleShot"] = "InventoryItems/firearms/weapon_shotgun_03_singleShot",
            ["weapon_shotgun_04_fullAuto_ZePSUTY"] = "InventoryItems/firearms/weapon_shotgun_04_fullAuto_ZePSUTY",
            ["weapon_shotgun_05_oneShot"] = "InventoryItems/firearms/weapon_shotgun_05_oneShot",
            ["weapon_submachine_01_full"] = "InventoryItems/firearms/weapon_submachine_01_full",
            ["book"] = "InventoryItems/home/book",
            ["home_apple"] = "InventoryItems/home/home_apple",
            ["home_chemical_bottle_01"] = "InventoryItems/home/home_chemical_bottle_01",
            ["home_chemical_bottle_02"] = "InventoryItems/home/home_chemical_bottle_02",
            ["home_chemical_spray_01"] = "InventoryItems/home/home_chemical_spray_01",
            ["home_clothes"] = "InventoryItems/home/home_clothes",
            ["home_money"] = "InventoryItems/home/home_money",
            ["home_pear"] = "InventoryItems/home/home_pear",
            ["home_scissor"] = "InventoryItems/home/home_scissor",
            ["home_shirt"] = "InventoryItems/home/home_shirt",
            ["home_towel"] = "InventoryItems/home/home_towel",
            ["aw_artur_drawings"] = "InventoryItems/journalItems/aw_artur_drawings",
            ["aw_grzegorz"] = "InventoryItems/journalItems/aw_grzegorz",
            ["aw_gutek"] = "InventoryItems/journalItems/aw_gutek",
            ["aw_ivanka"] = "InventoryItems/journalItems/aw_ivanka",
            ["aw_karolina"] = "InventoryItems/journalItems/aw_karolina",
            ["aw_killerfriend"] = "InventoryItems/journalItems/aw_killerfriend",
            ["aw_kuba"] = "InventoryItems/journalItems/aw_kuba",
            ["aw_maciek"] = "InventoryItems/journalItems/aw_maciek",
            ["aw_marcin"] = "InventoryItems/journalItems/aw_marcin",
            ["aw_mazyrun"] = "InventoryItems/journalItems/aw_mazyrun",
            ["aw_mugelisica"] = "InventoryItems/journalItems/aw_mugelisica",
            ["aw_mugelisica_2"] = "InventoryItems/journalItems/aw_mugelisica_2",
            ["aw_nullwinter"] = "InventoryItems/journalItems/aw_nullwinter",
            ["aw_piotrek"] = "InventoryItems/journalItems/aw_piotrek",
            ["book_wiedza_lekarska_01"] = "InventoryItems/journalItems/book_wiedza_lekarska_01",
            ["book_wiedza_lekarska_02"] = "InventoryItems/journalItems/book_wiedza_lekarska_02",
            ["book_wiedza_lekarska_02_burned"] = "InventoryItems/journalItems/book_wiedza_lekarska_02_burned",
            ["box_church"] = "InventoryItems/journalItems/box_church",
            ["box_church_drawings"] = "InventoryItems/journalItems/box_church_drawings",
            ["box_church_escaped"] = "InventoryItems/journalItems/box_church_escaped",
            ["box_church_key"] = "InventoryItems/journalItems/box_church_key",
            ["box_church_killedChomper"] = "InventoryItems/journalItems/box_church_killedChomper",
            ["bullet"] = "InventoryItems/journalItems/bullet",
            ["chicken_head_wolf_01"] = "InventoryItems/journalItems/chicken_head_wolf_01",
            ["cigarettes_klubowe"] = "InventoryItems/journalItems/cigarettes_klubowe",
            ["cigarettes_klubowe2"] = "InventoryItems/journalItems/cigarettes_klubowe2",
            ["cowbell_01"] = "InventoryItems/journalItems/cowbell_01",
            ["cowbell_02"] = "InventoryItems/journalItems/cowbell_02",
            ["cross_01_c"] = "InventoryItems/journalItems/cross_01_c",
            ["cross_03"] = "InventoryItems/journalItems/cross_03",
            ["doctor_note_baba_01"] = "InventoryItems/journalItems/doctor_note_baba_01",
            ["doctor_photo"] = "InventoryItems/journalItems/doctor_photo",
            ["doctor_wife_photo"] = "InventoryItems/journalItems/doctor_wife_photo",
            ["doll_01"] = "InventoryItems/journalItems/doll_01",
            ["doll_02"] = "InventoryItems/journalItems/doll_02",
            ["drewniana_kurka"] = "InventoryItems/journalItems/drewniana_kurka",
            ["drewniana_kurka_blood"] = "InventoryItems/journalItems/drewniana_kurka_blood",
            ["drewniana_kurka_dream"] = "InventoryItems/journalItems/drewniana_kurka_dream",
            ["drewniane_kurki"] = "InventoryItems/journalItems/drewniane_kurki",
            ["grannyPainting_01"] = "InventoryItems/journalItems/grannyPainting_01",
            ["grannyPainting_02"] = "InventoryItems/journalItems/grannyPainting_02",
            ["grannyPainting_03"] = "InventoryItems/journalItems/grannyPainting_03",
            ["grannyPainting_04"] = "InventoryItems/journalItems/grannyPainting_04",
            ["grannyPainting_05"] = "InventoryItems/journalItems/grannyPainting_05",
            ["head_nighttrader_01"] = "InventoryItems/journalItems/head_nighttrader_01",
            ["hunter_photo_1"] = "InventoryItems/journalItems/hunter_photo_1",
            ["jajeczka_wilk"] = "InventoryItems/journalItems/jajeczka_wilk",
            ["jar_epilogue"] = "InventoryItems/journalItems/jar_epilogue",
            ["jar_roadToHome"] = "InventoryItems/journalItems/jar_roadToHome",
            ["journal_clone"] = "InventoryItems/journalItems/journal_clone",
            ["kartkiEkspedycja"] = "InventoryItems/journalItems/kartkiEkspedycja",
            ["kasetaZniszczona"] = "InventoryItems/journalItems/kasetaZniszczona",
            ["kasztaniak"] = "InventoryItems/journalItems/kasztaniak",
            ["key_21"] = "InventoryItems/journalItems/key_21",
            ["key_21_clone"] = "InventoryItems/journalItems/key_21_clone",
            ["key_act1_biom3"] = "InventoryItems/journalItems/key_act1_biom3",
            ["key_baba_sister"] = "InventoryItems/journalItems/key_baba_sister",
            ["key_big_farm_02_shed"] = "InventoryItems/journalItems/key_big_farm_02_shed",
            ["key_border_burnedCottage"] = "InventoryItems/journalItems/key_border_burnedCottage",
            ["key_bunker_01_prologue"] = "InventoryItems/journalItems/key_bunker_01_prologue",
            ["key_bunker_act1"] = "InventoryItems/journalItems/key_bunker_act1",
            ["key_doctorHideout"] = "InventoryItems/journalItems/key_doctorHideout",
            ["key_dream_tutorial"] = "InventoryItems/journalItems/key_dream_tutorial",
            ["key_elephant_son_01"] = "InventoryItems/journalItems/key_elephant_son_01",
            ["key_epilog_sypialnia"] = "InventoryItems/journalItems/key_epilog_sypialnia",
            ["key_epilog_wyjscieZpokoju"] = "InventoryItems/journalItems/key_epilog_wyjscieZpokoju",
            ["key_med_cottage_tree_01_container"] = "InventoryItems/journalItems/key_med_cottage_tree_01_container",
            ["key_mushroomGranny_boy_01"] = "InventoryItems/journalItems/key_mushroomGranny_boy_01",
            ["key_outside_doctor_01_rozwalonyDom"] = "InventoryItems/journalItems/key_outside_doctor_01_rozwalonyDom",
            ["key_outside_village_ch1_cottage01_underground_01"] = "InventoryItems/journalItems/key_outside_village_ch1_cottage01_underground_01",
            ["key_radioTower_01"] = "InventoryItems/journalItems/key_radioTower_01",
            ["key_sawmill"] = "InventoryItems/journalItems/key_sawmill",
            ["key_snail_01"] = "InventoryItems/journalItems/key_snail_01",
            ["key_treeVillage_granny_01"] = "InventoryItems/journalItems/key_treeVillage_granny_01",
            ["key_treeVillage_mainKey"] = "InventoryItems/journalItems/key_treeVillage_mainKey",
            ["key_village_brother_key_01"] = "InventoryItems/journalItems/key_village_brother_key_01",
            ["key_wolfmanHideout_01"] = "InventoryItems/journalItems/key_wolfmanHideout_01",
            ["klisza"] = "InventoryItems/journalItems/klisza",
            ["kremCzekoladowy"] = "InventoryItems/journalItems/kremCzekoladowy",
            ["krzyzyk_01"] = "InventoryItems/journalItems/krzyzyk_01",
            ["lesnyLudek"] = "InventoryItems/journalItems/lesnyLudek",
            ["lotto"] = "InventoryItems/journalItems/lotto",
            ["magazynMotor_01"] = "InventoryItems/journalItems/magazynMotor_01",
            ["magazynPan_01"] = "InventoryItems/journalItems/magazynPan_01",
            ["magazynPlomyk_01"] = "InventoryItems/journalItems/magazynPlomyk_01",
            ["maszynaDoMiesa"] = "InventoryItems/journalItems/maszynaDoMiesa",
            ["medalion_brother"] = "InventoryItems/journalItems/medalion_brother",
            ["medalion_brother_02"] = "InventoryItems/journalItems/medalion_brother_02",
            ["medical_bag_burned_01"] = "InventoryItems/journalItems/medical_bag_burned_01",
            ["medical_tools_01"] = "InventoryItems/journalItems/medical_tools_01",
            ["medical_tools_02"] = "InventoryItems/journalItems/medical_tools_02",
            ["notatnik_doktora_01"] = "InventoryItems/journalItems/notatnik_doktora_01",
            ["notatnik_doktora_01_ch2_01"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_01",
            ["notatnik_doktora_01_ch2_02"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_02",
            ["notatnik_doktora_01_ch2_03"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_03",
            ["notatnik_doktora_01_ch2_04"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_04",
            ["notatnik_doktora_01_ch2_05"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_05",
            ["notatnik_doktora_01_ch2_06"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_06",
            ["notatnik_doktora_01_notka_01"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_01",
            ["notatnik_doktora_01_notka_02"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_02",
            ["notatnik_doktora_01_notka_03"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_03",
            ["notatnik_doktora_01_notka_kod"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_kod",
            ["notatnik_doktora_01_swamp_01"] = "InventoryItems/journalItems/notatnik_doktora_01_swamp_01",
            ["notatnik_doktora_burnedMap"] = "InventoryItems/journalItems/notatnik_doktora_burnedMap",
            ["note_burnedHouse_01"] = "InventoryItems/journalItems/note_burnedHouse_01",
            ["note_elephant_door"] = "InventoryItems/journalItems/note_elephant_door",
            ["note_elephant_picture"] = "InventoryItems/journalItems/note_elephant_picture",
            ["note_gagarin"] = "InventoryItems/journalItems/note_gagarin",
            ["note_gate_meadowForest_01"] = "InventoryItems/journalItems/note_gate_meadowForest_01",
            ["note_generator"] = "InventoryItems/journalItems/note_generator",
            ["note_hideout_swamp_01"] = "InventoryItems/journalItems/note_hideout_swamp_01",
            ["note_journal_bloody"] = "InventoryItems/journalItems/note_journal_bloody",
            ["note_kapelusznik_01"] = "InventoryItems/journalItems/note_kapelusznik_01",
            ["note_kapelusznik_02"] = "InventoryItems/journalItems/note_kapelusznik_02",
            ["note_kapelusznik_03"] = "InventoryItems/journalItems/note_kapelusznik_03",
            ["note_macius_1"] = "InventoryItems/journalItems/note_macius_1",
            ["note_macius_2"] = "InventoryItems/journalItems/note_macius_2",
            ["note_mail"] = "InventoryItems/journalItems/note_mail",
            ["note_mail_2"] = "InventoryItems/journalItems/note_mail_2",
            ["note_nightGiftMushroom_01"] = "InventoryItems/journalItems/note_nightGiftMushroom_01",
            ["note_pigshed_02"] = "InventoryItems/journalItems/note_pigshed_02",
            ["note_pigshed_flyer"] = "InventoryItems/journalItems/note_pigshed_flyer",
            ["note_przyjaciolka_wolf_01"] = "InventoryItems/journalItems/note_przyjaciolka_wolf_01",
            ["note_psalm91"] = "InventoryItems/journalItems/note_psalm91",
            ["note_radioTower_01"] = "InventoryItems/journalItems/note_radioTower_01",
            ["note_radioTower_02"] = "InventoryItems/journalItems/note_radioTower_02",
            ["note_rozdarteOpakowaniePapierosow"] = "InventoryItems/journalItems/note_rozdarteOpakowaniePapierosow",
            ["note_shadowarmor_01"] = "InventoryItems/journalItems/note_shadowarmor_01",
            ["note_signs_01"] = "InventoryItems/journalItems/note_signs_01",
            ["note_snail_journal_01"] = "InventoryItems/journalItems/note_snail_journal_01",
            ["note_snail_junk_01"] = "InventoryItems/journalItems/note_snail_junk_01",
            ["note_snail_numbers_01"] = "InventoryItems/journalItems/note_snail_numbers_01",
            ["note_theThree"] = "InventoryItems/journalItems/note_theThree",
            ["note_truck_01"] = "InventoryItems/journalItems/note_truck_01",
            ["note_villageTree_foodsupplies_01"] = "InventoryItems/journalItems/note_villageTree_foodsupplies_01",
            ["note_wallOfTrees_01"] = "InventoryItems/journalItems/note_wallOfTrees_01",
            ["note_wiazki_01"] = "InventoryItems/journalItems/note_wiazki_01",
            ["note_wilk_klucz"] = "InventoryItems/journalItems/note_wilk_klucz",
            ["note_wolfman_stolenItems"] = "InventoryItems/journalItems/note_wolfman_stolenItems",
            ["note_xmass"] = "InventoryItems/journalItems/note_xmass",
            ["obiadek"] = "InventoryItems/journalItems/obiadek",
            ["photo_brothers"] = "InventoryItems/journalItems/photo_brothers",
            ["photo_burnedCottage_01"] = "InventoryItems/journalItems/photo_burnedCottage_01",
            ["photo_burnedCottage_02"] = "InventoryItems/journalItems/photo_burnedCottage_02",
            ["photo_doctor"] = "InventoryItems/journalItems/photo_doctor",
            ["photo_forest_dog"] = "InventoryItems/journalItems/photo_forest_dog",
            ["photo_forest_redneck_01"] = "InventoryItems/journalItems/photo_forest_redneck_01",
            ["photo_forest_redneck_02"] = "InventoryItems/journalItems/photo_forest_redneck_02",
            ["photo_karmiciel"] = "InventoryItems/journalItems/photo_karmiciel",
            ["photo_mushroomGranny"] = "InventoryItems/journalItems/photo_mushroomGranny",
            ["photo_roadToHome"] = "InventoryItems/journalItems/photo_roadToHome",
            ["pingpong_01"] = "InventoryItems/journalItems/pingpong_01",
            ["porterWhistle_note"] = "InventoryItems/journalItems/porterWhistle_note",
            ["radio_small_01"] = "InventoryItems/journalItems/radio_small_01",
            ["radio_small_01c"] = "InventoryItems/journalItems/radio_small_01c",
            ["rock_blood"] = "InventoryItems/journalItems/rock_blood",
            ["rocket_blueprint_01"] = "InventoryItems/journalItems/rocket_blueprint_01",
            ["rope_journal"] = "InventoryItems/journalItems/rope_journal",
            ["rubber_boot"] = "InventoryItems/journalItems/rubber_boot",
            ["screwdriver_epilog"] = "InventoryItems/journalItems/screwdriver_epilog",
            ["shawl_sister_01"] = "InventoryItems/journalItems/shawl_sister_01",
            ["skrety_01"] = "InventoryItems/journalItems/skrety_01",
            ["swiecznik_01"] = "InventoryItems/journalItems/swiecznik_01",
            ["syfon"] = "InventoryItems/journalItems/syfon",
            ["syringe_01"] = "InventoryItems/journalItems/syringe_01",
            ["termometr"] = "InventoryItems/journalItems/termometr",
            ["trophy_wolf"] = "InventoryItems/journalItems/trophy_wolf",
            ["trybuna_ludu_01"] = "InventoryItems/journalItems/trybuna_ludu_01",
            ["twins_church_01"] = "InventoryItems/journalItems/twins_church_01",
            ["twins_church_01_dream"] = "InventoryItems/journalItems/twins_church_01_dream",
            ["unitra_doctor"] = "InventoryItems/journalItems/unitra_doctor",
            ["uzytek_z_grzybow_01"] = "InventoryItems/journalItems/uzytek_z_grzybow_01",
            ["violin_old"] = "InventoryItems/journalItems/violin_old",
            ["wedding_invitation"] = "InventoryItems/journalItems/wedding_invitation",
            ["wedding_invitation_2"] = "InventoryItems/journalItems/wedding_invitation_2",
            ["wedding_tape"] = "InventoryItems/journalItems/wedding_tape",
            ["white_dress"] = "InventoryItems/journalItems/white_dress",
            ["map"] = "InventoryItems/maps/map",
            ["map_bio2"] = "InventoryItems/maps/map_bio2",
            ["map_bio3"] = "InventoryItems/maps/map_bio3",
            ["map_borderBurned"] = "InventoryItems/maps/map_borderBurned",
            ["map_doctor_ch2"] = "InventoryItems/maps/map_doctor_ch2",
            ["map_doctorEntrance"] = "InventoryItems/maps/map_doctorEntrance",
            ["map_dziury"] = "InventoryItems/maps/map_dziury",
            ["map_mushrooms"] = "InventoryItems/maps/map_mushrooms",
            ["map_pigShed"] = "InventoryItems/maps/map_pigShed",
            ["map_piotrekPigsheds"] = "InventoryItems/maps/map_piotrekPigsheds",
            ["map_radioTower"] = "InventoryItems/maps/map_radioTower",
            ["map_trainWreck"] = "InventoryItems/maps/map_trainWreck",
            ["map_villageTree"] = "InventoryItems/maps/map_villageTree",
            ["axe_edge"] = "InventoryItems/materials/axe_edge",
            ["chitin"] = "InventoryItems/materials/chitin",
            ["compressor_parts_01"] = "InventoryItems/materials/compressor_parts_01",
            ["electronics"] = "InventoryItems/materials/electronics",
            ["fabric"] = "InventoryItems/materials/fabric",
            ["junk"] = "InventoryItems/materials/junk",
            ["nail"] = "InventoryItems/materials/nail",
            ["pincers"] = "InventoryItems/materials/pincers",
            ["pipe_metal"] = "InventoryItems/materials/pipe_metal",
            ["rag"] = "InventoryItems/materials/rag",
            ["rope"] = "InventoryItems/materials/rope",
            ["shovel_edge"] = "InventoryItems/materials/shovel_edge",
            ["spring"] = "InventoryItems/materials/spring",
            ["tape"] = "InventoryItems/materials/tape",
            ["toolbox"] = "InventoryItems/materials/toolbox",
            ["welder"] = "InventoryItems/materials/welder",
            ["wire"] = "InventoryItems/materials/wire",
            ["wood"] = "InventoryItems/materials/wood",
            ["woodLog"] = "InventoryItems/materials/woodLog",
            ["axe"] = "InventoryItems/meleeWeapons/axe",
            ["knife"] = "InventoryItems/meleeWeapons/knife",
            ["pitchfork"] = "InventoryItems/meleeWeapons/pitchfork",
            ["plank_nails"] = "InventoryItems/meleeWeapons/plank_nails",
            ["shovel"] = "InventoryItems/meleeWeapons/shovel",
            ["sickle"] = "InventoryItems/meleeWeapons/sickle",
            ["stick"] = "InventoryItems/meleeWeapons/stick",
            ["table_leg"] = "InventoryItems/meleeWeapons/table_leg",
            ["table_leg2"] = "InventoryItems/meleeWeapons/table_leg2",
            ["table_leg_oneChance"] = "InventoryItems/meleeWeapons/table_leg_oneChance",
            ["torch"] = "InventoryItems/meleeWeapons/torch",
            ["antler"] = "InventoryItems/misc/antler",
            ["bark_01"] = "InventoryItems/misc/bark_01",
            ["blanket_sister"] = "InventoryItems/misc/blanket_sister",
            ["bone"] = "InventoryItems/misc/bone",
            ["bucket"] = "InventoryItems/misc/bucket",
            ["cable"] = "InventoryItems/misc/cable",
            ["cassette"] = "InventoryItems/misc/cassette",
            ["cassette_dream_tut"] = "InventoryItems/misc/cassette_dream_tut",
            ["chain_well"] = "InventoryItems/misc/chain_well",
            ["chemical_bottle_01"] = "InventoryItems/misc/chemical_bottle_01",
            ["chicken_head"] = "InventoryItems/misc/chicken_head",
            ["cross_01"] = "InventoryItems/misc/cross_01",
            ["gasmask"] = "InventoryItems/misc/gasmask",
            ["gps_ear"] = "InventoryItems/misc/gps_ear",
            ["gps_finger"] = "InventoryItems/misc/gps_finger",
            ["gps_nose"] = "InventoryItems/misc/gps_nose",
            ["humanArm_01"] = "InventoryItems/misc/humanArm_01",
            ["humanEar_01"] = "InventoryItems/misc/humanEar_01",
            ["humanFinger_01"] = "InventoryItems/misc/humanFinger_01",
            ["humanLeg_01"] = "InventoryItems/misc/humanLeg_01",
            ["ice_01"] = "InventoryItems/misc/ice_01",
            ["kebab"] = "InventoryItems/misc/kebab",
            ["key_bunker_01_maskFamily"] = "InventoryItems/misc/key_bunker_01_maskFamily",
            ["kupaWilka"] = "InventoryItems/misc/kupaWilka",
            ["lockpick"] = "InventoryItems/misc/lockpick",
            ["mushroom_rotten"] = "InventoryItems/misc/mushroom_rotten",
            ["old_medical_bag"] = "InventoryItems/misc/old_medical_bag",
            ["pigHead"] = "InventoryItems/misc/pigHead",
            ["porterWhistle"] = "InventoryItems/misc/porterWhistle",
            ["ring2"] = "InventoryItems/misc/ring2",
            ["ring_wedding"] = "InventoryItems/misc/ring_wedding",
            ["ring_wedding_babahunter"] = "InventoryItems/misc/ring_wedding_babahunter",
            ["ring_wedding_babahunterCopy"] = "InventoryItems/misc/ring_wedding_babahunterCopy",
            ["rubberBoots"] = "InventoryItems/misc/rubberBoots",
            ["scalpel"] = "InventoryItems/misc/scalpel",
            ["shiny_rock"] = "InventoryItems/misc/shiny_rock",
            ["shiny_rock_cross"] = "InventoryItems/misc/shiny_rock_cross",
            ["stone_weird_01"] = "InventoryItems/misc/stone_weird_01",
            ["sweater"] = "InventoryItems/misc/sweater",
            ["teddyBear"] = "InventoryItems/misc/teddyBear",
            ["tooth"] = "InventoryItems/misc/tooth",
            ["toy_rocket"] = "InventoryItems/misc/toy_rocket",
            ["wheelsSmall"] = "InventoryItems/misc/wheelsSmall",
            ["zenit"] = "InventoryItems/misc/zenit",
            ["zenit_mud"] = "InventoryItems/misc/zenit_mud",
            ["player_epilogue_test_item"] = "InventoryItems/player_epilogue_test_item",
            ["hat_brother"] = "InventoryItems/questItems/hat_brother",
            ["note_musicianCard1"] = "InventoryItems/questItems/note_musicianCard1",
            ["oxygenTank_empty"] = "InventoryItems/questItems/oxygenTank_empty",
            ["oxygenTank_full"] = "InventoryItems/questItems/oxygenTank_full",
            ["piotrek_parts_1"] = "InventoryItems/questItems/piotrek_parts_1",
            ["piotrek_parts_2"] = "InventoryItems/questItems/piotrek_parts_2",
            ["piotrek_parts_3"] = "InventoryItems/questItems/piotrek_parts_3",
            ["piotrek_parts_4"] = "InventoryItems/questItems/piotrek_parts_4",
            ["piotrek_parts_5"] = "InventoryItems/questItems/piotrek_parts_5",
            ["piotrek_parts_6"] = "InventoryItems/questItems/piotrek_parts_6",
            ["violin"] = "InventoryItems/questItems/violin",
            ["flare"] = "InventoryItems/thrownItems/flare",
            ["gasBomb"] = "InventoryItems/thrownItems/gasBomb",
            ["matchstick"] = "InventoryItems/thrownItems/matchstick",
            ["meat"] = "InventoryItems/thrownItems/meat",
            ["meat_soporific"] = "InventoryItems/thrownItems/meat_soporific",
            ["molotov"] = "InventoryItems/thrownItems/molotov",
            ["noiseLure"] = "InventoryItems/thrownItems/noiseLure",
            ["stone"] = "InventoryItems/thrownItems/stone",
            ["barrelExploding"] = "InventoryItems/traps/barrelExploding",
            ["beartrap"] = "InventoryItems/traps/beartrap",
            ["bottle"] = "InventoryItems/traps/bottle",
            ["brokenGlass"] = "InventoryItems/traps/brokenGlass",
            ["chainTrap"] = "InventoryItems/traps/chainTrap",
            ["fartPillow"] = "InventoryItems/traps/fartPillow",
            ["gasBottle"] = "InventoryItems/traps/gasBottle",
            ["armor_light"] = "InventoryItems/useable/armor_light",
            ["flashlight"] = "InventoryItems/useable/flashlight",
            ["flashlight_02"] = "InventoryItems/useable/flashlight_02",
            ["flashlight_rechargable"] = "InventoryItems/useable/flashlight_rechargable",
            ["gasoline"] = "InventoryItems/useable/gasoline",
            ["hotbarPlus_01"] = "InventoryItems/useable/hotbarPlus_01",
            ["invPlus_01"] = "InventoryItems/useable/invPlus_01",
            ["lantern"] = "InventoryItems/useable/lantern",
            ["watch"] = "InventoryItems/useable/watch"
        };

        internal static Dictionary<string, string> JOURNAL_ITEMS = new()
        {
            ["aw_artur_drawings"] = "InventoryItems/journalItems/aw_artur_drawings",
            ["aw_grzegorz"] = "InventoryItems/journalItems/aw_grzegorz",
            ["aw_gutek"] = "InventoryItems/journalItems/aw_gutek",
            ["aw_ivanka"] = "InventoryItems/journalItems/aw_ivanka",
            ["aw_karolina"] = "InventoryItems/journalItems/aw_karolina",
            ["aw_killerfriend"] = "InventoryItems/journalItems/aw_killerfriend",
            ["aw_kuba"] = "InventoryItems/journalItems/aw_kuba",
            ["aw_maciek"] = "InventoryItems/journalItems/aw_maciek",
            ["aw_marcin"] = "InventoryItems/journalItems/aw_marcin",
            ["aw_mazyrun"] = "InventoryItems/journalItems/aw_mazyrun",
            ["aw_mugelisica"] = "InventoryItems/journalItems/aw_mugelisica",
            ["aw_mugelisica_2"] = "InventoryItems/journalItems/aw_mugelisica_2",
            ["aw_nullwinter"] = "InventoryItems/journalItems/aw_nullwinter",
            ["aw_piotrek"] = "InventoryItems/journalItems/aw_piotrek",
            ["book_wiedza_lekarska_01"] = "InventoryItems/journalItems/book_wiedza_lekarska_01",
            ["book_wiedza_lekarska_02"] = "InventoryItems/journalItems/book_wiedza_lekarska_02",
            ["book_wiedza_lekarska_02_burned"] = "InventoryItems/journalItems/book_wiedza_lekarska_02_burned",
            ["box_church"] = "InventoryItems/journalItems/box_church",
            ["box_church_drawings"] = "InventoryItems/journalItems/box_church_drawings",
            ["box_church_escaped"] = "InventoryItems/journalItems/box_church_escaped",
            ["box_church_killedChomper"] = "InventoryItems/journalItems/box_church_killedChomper",
            ["bullet"] = "InventoryItems/journalItems/bullet",
            ["chicken_head_wolf_01"] = "InventoryItems/journalItems/chicken_head_wolf_01",
            ["cigarettes_klubowe"] = "InventoryItems/journalItems/cigarettes_klubowe",
            ["cigarettes_klubowe2"] = "InventoryItems/journalItems/cigarettes_klubowe2",
            ["cowbell_01"] = "InventoryItems/journalItems/cowbell_01",
            ["cowbell_02"] = "InventoryItems/journalItems/cowbell_02",
            ["cross_01_c"] = "InventoryItems/journalItems/cross_01_c",
            ["cross_03"] = "InventoryItems/journalItems/cross_03",
            ["doctor_note_baba_01"] = "InventoryItems/journalItems/doctor_note_baba_01",
            ["doctor_photo"] = "InventoryItems/journalItems/doctor_photo",
            ["doctor_wife_photo"] = "InventoryItems/journalItems/doctor_wife_photo",
            ["doll_01"] = "InventoryItems/journalItems/doll_01",
            ["doll_02"] = "InventoryItems/journalItems/doll_02",
            ["drewniana_kurka"] = "InventoryItems/journalItems/drewniana_kurka",
            ["drewniana_kurka_blood"] = "InventoryItems/journalItems/drewniana_kurka_blood",
            ["drewniana_kurka_dream"] = "InventoryItems/journalItems/drewniana_kurka_dream",
            ["drewniane_kurki"] = "InventoryItems/journalItems/drewniane_kurki",
            ["grannyPainting_01"] = "InventoryItems/journalItems/grannyPainting_01",
            ["grannyPainting_02"] = "InventoryItems/journalItems/grannyPainting_02",
            ["grannyPainting_03"] = "InventoryItems/journalItems/grannyPainting_03",
            ["grannyPainting_04"] = "InventoryItems/journalItems/grannyPainting_04",
            ["grannyPainting_05"] = "InventoryItems/journalItems/grannyPainting_05",
            ["head_nighttrader_01"] = "InventoryItems/journalItems/head_nighttrader_01",
            ["hunter_photo_1"] = "InventoryItems/journalItems/hunter_photo_1",
            ["jajeczka_wilk"] = "InventoryItems/journalItems/jajeczka_wilk",
            ["jar_epilogue"] = "InventoryItems/journalItems/jar_epilogue",
            ["jar_roadToHome"] = "InventoryItems/journalItems/jar_roadToHome",
            ["journal_clone"] = "InventoryItems/journalItems/journal_clone",
            ["kartkiEkspedycja"] = "InventoryItems/journalItems/kartkiEkspedycja",
            ["kasetaZniszczona"] = "InventoryItems/journalItems/kasetaZniszczona",
            ["kasztaniak"] = "InventoryItems/journalItems/kasztaniak",
            ["klisza"] = "InventoryItems/journalItems/klisza",
            ["kremCzekoladowy"] = "InventoryItems/journalItems/kremCzekoladowy",
            ["krzyzyk_01"] = "InventoryItems/journalItems/krzyzyk_01",
            ["lesnyLudek"] = "InventoryItems/journalItems/lesnyLudek",
            ["lotto"] = "InventoryItems/journalItems/lotto",
            ["magazynMotor_01"] = "InventoryItems/journalItems/magazynMotor_01",
            ["magazynPan_01"] = "InventoryItems/journalItems/magazynPan_01",
            ["magazynPlomyk_01"] = "InventoryItems/journalItems/magazynPlomyk_01",
            ["maszynaDoMiesa"] = "InventoryItems/journalItems/maszynaDoMiesa",
            ["medalion_brother"] = "InventoryItems/journalItems/medalion_brother",
            ["medalion_brother_02"] = "InventoryItems/journalItems/medalion_brother_02",
            ["medical_bag_burned_01"] = "InventoryItems/journalItems/medical_bag_burned_01",
            ["medical_tools_01"] = "InventoryItems/journalItems/medical_tools_01",
            ["medical_tools_02"] = "InventoryItems/journalItems/medical_tools_02",
            ["notatnik_doktora_01"] = "InventoryItems/journalItems/notatnik_doktora_01",
            ["notatnik_doktora_01_ch2_01"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_01",
            ["notatnik_doktora_01_ch2_02"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_02",
            ["notatnik_doktora_01_ch2_03"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_03",
            ["notatnik_doktora_01_ch2_04"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_04",
            ["notatnik_doktora_01_ch2_05"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_05",
            ["notatnik_doktora_01_ch2_06"] = "InventoryItems/journalItems/notatnik_doktora_01_ch2_06",
            ["notatnik_doktora_01_notka_01"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_01",
            ["notatnik_doktora_01_notka_02"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_02",
            ["notatnik_doktora_01_notka_03"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_03",
            ["notatnik_doktora_01_notka_kod"] = "InventoryItems/journalItems/notatnik_doktora_01_notka_kod",
            ["notatnik_doktora_01_swamp_01"] = "InventoryItems/journalItems/notatnik_doktora_01_swamp_01",
            ["notatnik_doktora_burnedMap"] = "InventoryItems/journalItems/notatnik_doktora_burnedMap",
            ["note_burnedHouse_01"] = "InventoryItems/journalItems/note_burnedHouse_01",
            ["note_elephant_door"] = "InventoryItems/journalItems/note_elephant_door",
            ["note_elephant_picture"] = "InventoryItems/journalItems/note_elephant_picture",
            ["note_gagarin"] = "InventoryItems/journalItems/note_gagarin",
            ["note_gate_meadowForest_01"] = "InventoryItems/journalItems/note_gate_meadowForest_01",
            ["note_generator"] = "InventoryItems/journalItems/note_generator",
            ["note_hideout_swamp_01"] = "InventoryItems/journalItems/note_hideout_swamp_01",
            ["note_journal_bloody"] = "InventoryItems/journalItems/note_journal_bloody",
            ["note_kapelusznik_01"] = "InventoryItems/journalItems/note_kapelusznik_01",
            ["note_kapelusznik_02"] = "InventoryItems/journalItems/note_kapelusznik_02",
            ["note_kapelusznik_03"] = "InventoryItems/journalItems/note_kapelusznik_03",
            ["note_macius_1"] = "InventoryItems/journalItems/note_macius_1",
            ["note_macius_2"] = "InventoryItems/journalItems/note_macius_2",
            ["note_mail"] = "InventoryItems/journalItems/note_mail",
            ["note_mail_2"] = "InventoryItems/journalItems/note_mail_2",
            ["note_nightGiftMushroom_01"] = "InventoryItems/journalItems/note_nightGiftMushroom_01",
            ["note_pigshed_02"] = "InventoryItems/journalItems/note_pigshed_02",
            ["note_pigshed_flyer"] = "InventoryItems/journalItems/note_pigshed_flyer",
            ["note_przyjaciolka_wolf_01"] = "InventoryItems/journalItems/note_przyjaciolka_wolf_01",
            ["note_psalm91"] = "InventoryItems/journalItems/note_psalm91",
            ["note_radioTower_01"] = "InventoryItems/journalItems/note_radioTower_01",
            ["note_radioTower_02"] = "InventoryItems/journalItems/note_radioTower_02",
            ["note_rozdarteOpakowaniePapierosow"] = "InventoryItems/journalItems/note_rozdarteOpakowaniePapierosow",
            ["note_shadowarmor_01"] = "InventoryItems/journalItems/note_shadowarmor_01",
            ["note_signs_01"] = "InventoryItems/journalItems/note_signs_01",
            ["note_snail_journal_01"] = "InventoryItems/journalItems/note_snail_journal_01",
            ["note_snail_junk_01"] = "InventoryItems/journalItems/note_snail_junk_01",
            ["note_snail_numbers_01"] = "InventoryItems/journalItems/note_snail_numbers_01",
            ["note_theThree"] = "InventoryItems/journalItems/note_theThree",
            ["note_truck_01"] = "InventoryItems/journalItems/note_truck_01",
            ["note_villageTree_foodsupplies_01"] = "InventoryItems/journalItems/note_villageTree_foodsupplies_01",
            ["note_wallOfTrees_01"] = "InventoryItems/journalItems/note_wallOfTrees_01",
            ["note_wiazki_01"] = "InventoryItems/journalItems/note_wiazki_01",
            ["note_wilk_klucz"] = "InventoryItems/journalItems/note_wilk_klucz",
            ["note_wolfman_stolenItems"] = "InventoryItems/journalItems/note_wolfman_stolenItems",
            ["note_xmass"] = "InventoryItems/journalItems/note_xmass",
            ["obiadek"] = "InventoryItems/journalItems/obiadek",
            ["photo_brothers"] = "InventoryItems/journalItems/photo_brothers",
            ["photo_burnedCottage_01"] = "InventoryItems/journalItems/photo_burnedCottage_01",
            ["photo_burnedCottage_02"] = "InventoryItems/journalItems/photo_burnedCottage_02",
            ["photo_doctor"] = "InventoryItems/journalItems/photo_doctor",
            ["photo_forest_dog"] = "InventoryItems/journalItems/photo_forest_dog",
            ["photo_forest_redneck_01"] = "InventoryItems/journalItems/photo_forest_redneck_01",
            ["photo_forest_redneck_02"] = "InventoryItems/journalItems/photo_forest_redneck_02",
            ["photo_karmiciel"] = "InventoryItems/journalItems/photo_karmiciel",
            ["photo_mushroomGranny"] = "InventoryItems/journalItems/photo_mushroomGranny",
            ["photo_roadToHome"] = "InventoryItems/journalItems/photo_roadToHome",
            ["pingpong_01"] = "InventoryItems/journalItems/pingpong_01",
            ["porterWhistle_note"] = "InventoryItems/journalItems/porterWhistle_note",
            ["radio_small_01"] = "InventoryItems/journalItems/radio_small_01",
            ["radio_small_01c"] = "InventoryItems/journalItems/radio_small_01c",
            ["rock_blood"] = "InventoryItems/journalItems/rock_blood",
            ["rocket_blueprint_01"] = "InventoryItems/journalItems/rocket_blueprint_01",
            ["rope_journal"] = "InventoryItems/journalItems/rope_journal",
            ["rubber_boot"] = "InventoryItems/journalItems/rubber_boot",
            ["screwdriver_epilog"] = "InventoryItems/journalItems/screwdriver_epilog",
            ["shawl_sister_01"] = "InventoryItems/journalItems/shawl_sister_01",
            ["skrety_01"] = "InventoryItems/journalItems/skrety_01",
            ["swiecznik_01"] = "InventoryItems/journalItems/swiecznik_01",
            ["syfon"] = "InventoryItems/journalItems/syfon",
            ["syringe_01"] = "InventoryItems/journalItems/syringe_01",
            ["termometr"] = "InventoryItems/journalItems/termometr",
            ["trophy_wolf"] = "InventoryItems/journalItems/trophy_wolf",
            ["trybuna_ludu_01"] = "InventoryItems/journalItems/trybuna_ludu_01",
            ["twins_church_01"] = "InventoryItems/journalItems/twins_church_01",
            ["twins_church_01_dream"] = "InventoryItems/journalItems/twins_church_01_dream",
            ["unitra_doctor"] = "InventoryItems/journalItems/unitra_doctor",
            ["uzytek_z_grzybow_01"] = "InventoryItems/journalItems/uzytek_z_grzybow_01",
            ["violin_old"] = "InventoryItems/journalItems/violin_old",
            ["wedding_invitation"] = "InventoryItems/journalItems/wedding_invitation",
            ["wedding_invitation_2"] = "InventoryItems/journalItems/wedding_invitation_2",
            ["wedding_tape"] = "InventoryItems/journalItems/wedding_tape",
            ["white_dress"] = "InventoryItems/journalItems/white_dress"
        };

        internal static Dictionary<string, string> KEY_ITEMS = new()
        {
            ["box_church_key"] = "InventoryItems/journalItems/box_church_key",
            ["key_21"] = "InventoryItems/journalItems/key_21",
            ["key_21_clone"] = "InventoryItems/journalItems/key_21_clone",
            ["key_act1_biom3"] = "InventoryItems/journalItems/key_act1_biom3",
            ["key_baba_sister"] = "InventoryItems/journalItems/key_baba_sister",
            ["key_big_farm_02_shed"] = "InventoryItems/journalItems/key_big_farm_02_shed",
            ["key_border_burnedCottage"] = "InventoryItems/journalItems/key_border_burnedCottage",
            ["key_bunker_01_prologue"] = "InventoryItems/journalItems/key_bunker_01_prologue",
            ["key_bunker_act1"] = "InventoryItems/journalItems/key_bunker_act1",
            ["key_doctorHideout"] = "InventoryItems/journalItems/key_doctorHideout",
            ["key_dream_tutorial"] = "InventoryItems/journalItems/key_dream_tutorial",
            ["key_elephant_son_01"] = "InventoryItems/journalItems/key_elephant_son_01",
            ["key_epilog_sypialnia"] = "InventoryItems/journalItems/key_epilog_sypialnia",
            ["key_epilog_wyjscieZpokoju"] = "InventoryItems/journalItems/key_epilog_wyjscieZpokoju",
            ["key_med_cottage_tree_01_container"] = "InventoryItems/journalItems/key_med_cottage_tree_01_container",
            ["key_mushroomGranny_boy_01"] = "InventoryItems/journalItems/key_mushroomGranny_boy_01",
            ["key_outside_doctor_01_rozwalonyDom"] = "InventoryItems/journalItems/key_outside_doctor_01_rozwalonyDom",
            ["key_outside_village_ch1_cottage01_underground_01"] = "InventoryItems/journalItems/key_outside_village_ch1_cottage01_underground_01",
            ["key_radioTower_01"] = "InventoryItems/journalItems/key_radioTower_01",
            ["key_sawmill"] = "InventoryItems/journalItems/key_sawmill",
            ["key_snail_01"] = "InventoryItems/journalItems/key_snail_01",
            ["key_treeVillage_granny_01"] = "InventoryItems/journalItems/key_treeVillage_granny_01",
            ["key_treeVillage_mainKey"] = "InventoryItems/journalItems/key_treeVillage_mainKey",
            ["key_village_brother_key_01"] = "InventoryItems/journalItems/key_village_brother_key_01",
            ["key_wolfmanHideout_01"] = "InventoryItems/journalItems/key_wolfmanHideout_01"
        };

        internal static Dictionary<string, string> WEAPON_ITEMS = new()
        {

            ["firecraft_boltHandle"] = "InventoryItems/firearms/firecraft_boltHandle",
            ["firecraft_handgunFrame"] = "InventoryItems/firearms/firecraft_handgunFrame",
            ["firecraft_longBarrel"] = "InventoryItems/firearms/firecraft_longBarrel",
            ["firecraft_tubularMagazine"] = "InventoryItems/firearms/firecraft_tubularMagazine",
            ["firecraft_weaponParts"] = "InventoryItems/firearms/firecraft_weaponParts",
            ["weapon_assault_01_burst"] = "InventoryItems/firearms/weapon_assault_01_burst",
            ["weapon_flamethrower_homeMade"] = "InventoryItems/firearms/weapon_flamethrower_homeMade",
            ["weapon_flamethrower_military"] = "InventoryItems/firearms/weapon_flamethrower_military",
            ["weapon_pistol_01_pellet"] = "InventoryItems/firearms/weapon_pistol_01_pellet",
            ["weapon_pistol_02_semi"] = "InventoryItems/firearms/weapon_pistol_02_semi",
            ["weapon_pistol_03_oneShot"] = "InventoryItems/firearms/weapon_pistol_03_oneShot",
            ["weapon_rifle_01_pellet"] = "InventoryItems/firearms/weapon_rifle_01_pellet",
            ["weapon_rifle_02_boltAction"] = "InventoryItems/firearms/weapon_rifle_02_boltAction",
            ["weapon_shotgun_01_breakAction_Double"] = "InventoryItems/firearms/weapon_shotgun_01_breakAction_Double",
            ["weapon_shotgun_02_pumpAction"] = "InventoryItems/firearms/weapon_shotgun_02_pumpAction",
            ["weapon_shotgun_03_singleShot"] = "InventoryItems/firearms/weapon_shotgun_03_singleShot",
            ["weapon_shotgun_04_fullAuto_ZePSUTY"] = "InventoryItems/firearms/weapon_shotgun_04_fullAuto_ZePSUTY",
            ["weapon_shotgun_05_oneShot"] = "InventoryItems/firearms/weapon_shotgun_05_oneShot",
            ["weapon_submachine_01_full"] = "InventoryItems/firearms/weapon_submachine_01_full",
            ["axe"] = "InventoryItems/meleeWeapons/axe",
            ["knife"] = "InventoryItems/meleeWeapons/knife",
            ["pitchfork"] = "InventoryItems/meleeWeapons/pitchfork",
            ["plank_nails"] = "InventoryItems/meleeWeapons/plank_nails",
            ["shovel"] = "InventoryItems/meleeWeapons/shovel",
            ["sickle"] = "InventoryItems/meleeWeapons/sickle",
            ["stick"] = "InventoryItems/meleeWeapons/stick",
            ["table_leg"] = "InventoryItems/meleeWeapons/table_leg",
            ["table_leg2"] = "InventoryItems/meleeWeapons/table_leg2",
            ["table_leg_oneChance"] = "InventoryItems/meleeWeapons/table_leg_oneChance",
            ["torch"] = "InventoryItems/meleeWeapons/torch"
        };

        internal static Dictionary<string, string> CONSUMABLE_ITEMS = new()
        {
            ["acid"] = "InventoryItems/consumables/acid",
            ["alcohol"] = "InventoryItems/consumables/alcohol",
            ["antidote_poison"] = "InventoryItems/consumables/antidote_poison",
            ["bandages"] = "InventoryItems/consumables/bandages",
            ["bandages_alcohol"] = "InventoryItems/consumables/bandages_alcohol",
            ["bread"] = "InventoryItems/consumables/bread",
            ["chicken_egg"] = "InventoryItems/consumables/chicken_egg",
            ["chicken_egg_red"] = "InventoryItems/consumables/chicken_egg_red",
            ["dead_rat"] = "InventoryItems/consumables/dead_rat",
            ["fish"] = "InventoryItems/consumables/fish",
            ["lifePotion"] = "InventoryItems/consumables/lifePotion",
            ["pills"] = "InventoryItems/consumables/pills",
            ["pills_02"] = "InventoryItems/consumables/pills_02",
            ["potato_01"] = "InventoryItems/consumables/potato_01",
            ["soup_01"] = "InventoryItems/consumables/soup_01"
        };

        internal static Dictionary<string, string> HOME_ITEMS = new()
        {
            ["book"] = "InventoryItems/home/book",
            ["home_apple"] = "InventoryItems/home/home_apple",
            ["home_chemical_bottle_01"] = "InventoryItems/home/home_chemical_bottle_01",
            ["home_chemical_bottle_02"] = "InventoryItems/home/home_chemical_bottle_02",
            ["home_chemical_spray_01"] = "InventoryItems/home/home_chemical_spray_01",
            ["home_clothes"] = "InventoryItems/home/home_clothes",
            ["home_money"] = "InventoryItems/home/home_money",
            ["home_pear"] = "InventoryItems/home/home_pear",
            ["home_scissor"] = "InventoryItems/home/home_scissor",
            ["home_shirt"] = "InventoryItems/home/home_shirt",
            ["home_towel"] = "InventoryItems/home/home_towel"
        };

        internal static Dictionary<string, string> DEBUG_ITEMS = new()
        {
            ["fists"] = "InventoryItems/_other/fists",
            ["hammer"] = "InventoryItems/_other/hammer",
            ["healthUpgrade"] = "InventoryItems/_other/healthUpgrade",
            ["playerUpgradeIngredient"] = "InventoryItems/_other/playerUpgradeIngredient",
            ["recipe"] = "InventoryItems/_other/recipe",
            ["staminaUpgrade"] = "InventoryItems/_other/staminaUpgrade",
            ["workbenchUpgrade_01"] = "InventoryItems/_other/workbenchUpgrade_01",
            ["workbenchUpgrade_02"] = "InventoryItems/_other/workbenchUpgrade_02",
            ["workbenchUpgrade_03"] = "InventoryItems/_other/workbenchUpgrade_03",
            ["workbenchUpgrade_04"] = "InventoryItems/_other/workbenchUpgrade_04",
            ["workbenchUpgrade_05"] = "InventoryItems/_other/workbenchUpgrade_05",
            ["workbenchUpgrade_06"] = "InventoryItems/_other/workbenchUpgrade_06",
            ["workbenchUpgrade_07"] = "InventoryItems/_other/workbenchUpgrade_07",
            ["workbenchUpgrade_08"] = "InventoryItems/_other/workbenchUpgrade_08"
        };

        internal static Dictionary<string, string> XP_ITEMS = new()
        {
            ["exp_bio2_meat_mutated"] = "InventoryItems/expObjs/exp_bio2_meat_mutated",
            ["exp_bio2_mushroom_01"] = "InventoryItems/expObjs/exp_bio2_mushroom_01",
            ["exp_bio2_nightMushroom_01"] = "InventoryItems/expObjs/exp_bio2_nightMushroom_01",
            ["exp_bio3_meat_mutated"] = "InventoryItems/expObjs/exp_bio3_meat_mutated",
            ["exp_bio3_mushroom_meat_01"] = "InventoryItems/expObjs/exp_bio3_mushroom_meat_01",
            ["exp_bio3_nightMushroom_01"] = "InventoryItems/expObjs/exp_bio3_nightMushroom_01",
            ["exp_cockroach_mutated"] = "InventoryItems/expObjs/exp_cockroach_mutated",
            ["exp_epickiEXP"] = "InventoryItems/expObjs/exp_epickiEXP",
            ["exp_meat_mutated"] = "InventoryItems/expObjs/exp_meat_mutated",
            ["exp_mushroom"] = "InventoryItems/expObjs/exp_mushroom",
            ["exp_nightMushroom"] = "InventoryItems/expObjs/exp_nightMushroom",
            ["exp_piskle"] = "InventoryItems/expObjs/exp_piskle"
        };

        internal static Dictionary<string, string> MAP_ITEMS = new()
        {
            ["map"] = "InventoryItems/maps/map",
            ["map_bio2"] = "InventoryItems/maps/map_bio2",
            ["map_bio3"] = "InventoryItems/maps/map_bio3",
            ["map_borderBurned"] = "InventoryItems/maps/map_borderBurned",
            ["map_doctor_ch2"] = "InventoryItems/maps/map_doctor_ch2",
            ["map_doctorEntrance"] = "InventoryItems/maps/map_doctorEntrance",
            ["map_dziury"] = "InventoryItems/maps/map_dziury",
            ["map_mushrooms"] = "InventoryItems/maps/map_mushrooms",
            ["map_pigShed"] = "InventoryItems/maps/map_pigShed",
            ["map_piotrekPigsheds"] = "InventoryItems/maps/map_piotrekPigsheds",
            ["map_radioTower"] = "InventoryItems/maps/map_radioTower",
            ["map_trainWreck"] = "InventoryItems/maps/map_trainWreck",
            ["map_villageTree"] = "InventoryItems/maps/map_villageTree"
        };

        internal static Dictionary<string, string> AMMO_ITEMS = new()
        {
            ["ammo_clip_mediumCal"] = "InventoryItems/ammo/ammo_clip_mediumCal",
            ["ammo_clip_smallCal"] = "InventoryItems/ammo/ammo_clip_smallCal",
            ["ammo_single_mediumCal"] = "InventoryItems/ammo/ammo_single_mediumCal",
            ["ammo_single_pellet"] = "InventoryItems/ammo/ammo_single_pellet",
            ["ammo_single_shotgun"] = "InventoryItems/ammo/ammo_single_shotgun",
            ["battery9v"] = "InventoryItems/ammo/battery9v"
        };

        internal static Dictionary<string, string> MATERIAL_ITEMS = new()
        {
            ["axe_edge"] = "InventoryItems/materials/axe_edge",
            ["chitin"] = "InventoryItems/materials/chitin",
            ["compressor_parts_01"] = "InventoryItems/materials/compressor_parts_01",
            ["electronics"] = "InventoryItems/materials/electronics",
            ["fabric"] = "InventoryItems/materials/fabric",
            ["junk"] = "InventoryItems/materials/junk",
            ["nail"] = "InventoryItems/materials/nail",
            ["pincers"] = "InventoryItems/materials/pincers",
            ["pipe_metal"] = "InventoryItems/materials/pipe_metal",
            ["rag"] = "InventoryItems/materials/rag",
            ["rope"] = "InventoryItems/materials/rope",
            ["shovel_edge"] = "InventoryItems/materials/shovel_edge",
            ["spring"] = "InventoryItems/materials/spring",
            ["tape"] = "InventoryItems/materials/tape",
            ["toolbox"] = "InventoryItems/materials/toolbox",
            ["welder"] = "InventoryItems/materials/welder",
            ["wire"] = "InventoryItems/materials/wire",
            ["wood"] = "InventoryItems/materials/wood",
            ["woodLog"] = "InventoryItems/materials/woodLog"
        };

        internal static Dictionary<string, string> MISC_ITEMS = new()
        {
            ["antler"] = "InventoryItems/misc/antler",
            ["bark_01"] = "InventoryItems/misc/bark_01",
            ["blanket_sister"] = "InventoryItems/misc/blanket_sister",
            ["bone"] = "InventoryItems/misc/bone",
            ["bucket"] = "InventoryItems/misc/bucket",
            ["cable"] = "InventoryItems/misc/cable",
            ["cassette"] = "InventoryItems/misc/cassette",
            ["cassette_dream_tut"] = "InventoryItems/misc/cassette_dream_tut",
            ["chain_well"] = "InventoryItems/misc/chain_well",
            ["chemical_bottle_01"] = "InventoryItems/misc/chemical_bottle_01",
            ["chicken_head"] = "InventoryItems/misc/chicken_head",
            ["cross_01"] = "InventoryItems/misc/cross_01",
            ["gasmask"] = "InventoryItems/misc/gasmask",
            ["gps_ear"] = "InventoryItems/misc/gps_ear",
            ["gps_finger"] = "InventoryItems/misc/gps_finger",
            ["gps_nose"] = "InventoryItems/misc/gps_nose",
            ["humanArm_01"] = "InventoryItems/misc/humanArm_01",
            ["humanEar_01"] = "InventoryItems/misc/humanEar_01",
            ["humanFinger_01"] = "InventoryItems/misc/humanFinger_01",
            ["humanLeg_01"] = "InventoryItems/misc/humanLeg_01",
            ["ice_01"] = "InventoryItems/misc/ice_01",
            ["kebab"] = "InventoryItems/misc/kebab",
            ["key_bunker_01_maskFamily"] = "InventoryItems/misc/key_bunker_01_maskFamily",
            ["kupaWilka"] = "InventoryItems/misc/kupaWilka",
            ["lockpick"] = "InventoryItems/misc/lockpick",
            ["mushroom_rotten"] = "InventoryItems/misc/mushroom_rotten",
            ["old_medical_bag"] = "InventoryItems/misc/old_medical_bag",
            ["pigHead"] = "InventoryItems/misc/pigHead",
            ["porterWhistle"] = "InventoryItems/misc/porterWhistle",
            ["ring2"] = "InventoryItems/misc/ring2",
            ["ring_wedding"] = "InventoryItems/misc/ring_wedding",
            ["ring_wedding_babahunter"] = "InventoryItems/misc/ring_wedding_babahunter",
            ["ring_wedding_babahunterCopy"] = "InventoryItems/misc/ring_wedding_babahunterCopy",
            ["rubberBoots"] = "InventoryItems/misc/rubberBoots",
            ["scalpel"] = "InventoryItems/misc/scalpel",
            ["shiny_rock"] = "InventoryItems/misc/shiny_rock",
            ["shiny_rock_cross"] = "InventoryItems/misc/shiny_rock_cross",
            ["stone_weird_01"] = "InventoryItems/misc/stone_weird_01",
            ["sweater"] = "InventoryItems/misc/sweater",
            ["teddyBear"] = "InventoryItems/misc/teddyBear",
            ["tooth"] = "InventoryItems/misc/tooth",
            ["toy_rocket"] = "InventoryItems/misc/toy_rocket",
            ["wheelsSmall"] = "InventoryItems/misc/wheelsSmall",
            ["zenit"] = "InventoryItems/misc/zenit",
            ["zenit_mud"] = "InventoryItems/misc/zenit_mud"
        };

        internal static Dictionary<string, string> UTILITY_ITEMS = new()
        {
            ["armor_light"] = "InventoryItems/useable/armor_light",
            ["flashlight"] = "InventoryItems/useable/flashlight",
            ["flashlight_02"] = "InventoryItems/useable/flashlight_02",
            ["flashlight_rechargable"] = "InventoryItems/useable/flashlight_rechargable",
            ["gasoline"] = "InventoryItems/useable/gasoline",
            ["hotbarPlus_01"] = "InventoryItems/useable/hotbarPlus_01",
            ["invPlus_01"] = "InventoryItems/useable/invPlus_01",
            ["lantern"] = "InventoryItems/useable/lantern",
            ["watch"] = "InventoryItems/useable/watch"
        };

        internal static Dictionary<string, string> TRAP_ITEMS = new()
        {
            ["barrelExploding"] = "InventoryItems/traps/barrelExploding",
            ["beartrap"] = "InventoryItems/traps/beartrap",
            ["bottle"] = "InventoryItems/traps/bottle",
            ["brokenGlass"] = "InventoryItems/traps/brokenGlass",
            ["chainTrap"] = "InventoryItems/traps/chainTrap",
            ["fartPillow"] = "InventoryItems/traps/fartPillow",
            ["gasBottle"] = "InventoryItems/traps/gasBottle"
        };

        internal static Dictionary<string, string> THROWN_ITEMS = new()
        {
            ["flare"] = "InventoryItems/thrownItems/flare",
            ["gasBomb"] = "InventoryItems/thrownItems/gasBomb",
            ["matchstick"] = "InventoryItems/thrownItems/matchstick",
            ["meat"] = "InventoryItems/thrownItems/meat",
            ["meat_soporific"] = "InventoryItems/thrownItems/meat_soporific",
            ["molotov"] = "InventoryItems/thrownItems/molotov",
            ["noiseLure"] = "InventoryItems/thrownItems/noiseLure",
            ["stone"] = "InventoryItems/thrownItems/stone"
        };

        internal static Dictionary<string, string> QUEST_ITEMS = new()
        {
            ["hat_brother"] = "InventoryItems/questItems/hat_brother",
            ["note_musicianCard1"] = "InventoryItems/questItems/note_musicianCard1",
            ["oxygenTank_empty"] = "InventoryItems/questItems/oxygenTank_empty",
            ["oxygenTank_full"] = "InventoryItems/questItems/oxygenTank_full",
            ["piotrek_parts_1"] = "InventoryItems/questItems/piotrek_parts_1",
            ["piotrek_parts_2"] = "InventoryItems/questItems/piotrek_parts_2",
            ["piotrek_parts_3"] = "InventoryItems/questItems/piotrek_parts_3",
            ["piotrek_parts_4"] = "InventoryItems/questItems/piotrek_parts_4",
            ["piotrek_parts_5"] = "InventoryItems/questItems/piotrek_parts_5",
            ["piotrek_parts_6"] = "InventoryItems/questItems/piotrek_parts_6",
            ["violin"] = "InventoryItems/questItems/violin"
        };
    }
}
